### ISSUE TITLE
Muscle targets

### ISSUE THREAD

**Issue by android272** [everkinetic/data#2]
Could you possibly add into your drawings which muscles are being targeted? Kida like the pictures on the workout equipment.

![pull-ups-large-1](https://user-images.githubusercontent.com/5912527/31911185-d136acba-b80d-11e7-81db-aa21faef1339.png)
![pull-ups-large-2](https://user-images.githubusercontent.com/5912527/31911186-d1470074-b80d-11e7-9235-97f7d065fc09.png)

**Comment by solygen** [comment]
It's a nice idea to add this information. But i would prefer to keep also the orginal images to still have a choice.

Unfortunatly i really do not have any spare time for this project so you are very welcome to add this information by yourself

**Comment by JAlbertoGonzalez** [comment]
Being SVG images, would be easy to add a layer that can be switched on/off at choice. The hard work is to paint it in each image.
