### ISSUE TITLE
Can I use your image files?

### ISSUE THREAD

**Issue by Gongcu** [everkinetic/data#7]
Hi, I m a student in a college. I'm trying to develope a fitness app. Your image files so amazing and useful. If you do not mind, I want to use yours. Thanks for reading.

**Comment by solygen** [comment]
Yes sure. But please take a look at the conditions at https://github.com/everkinetic/data/blob/develop/LICENSE.md.

**Comment by Gongcu** [comment]
Thank you for your hard work.

**Comment by FedjaW** [comment]
Hello solygen, I am searching for exercise images for my fitness app and like your work very much. Can these images be used commercially? I had a really hard time to understand the licence conditions. There is a sentence "Not recommended for software", what scares me.

**Comment by solygen** [comment]
Hey FedjaW, 
maybe a visit at https://creativecommons.org/licenses/by-sa/4.0/ helps here.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/1290625/154809998-5e1a1c0a-2bc7-40a7-ac4d-5095e9172c01.png">

In other words. You could use it commercially but you have to give credit. In case you change or transform parts of it you have to share them (and only them, not you rwhole software) under the same license.

Hope that helps.
